[package]
name = "polar_to_osc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arctic = "1.0.0"
tokio = "1.35.1"
rosc = "~0.10"
